import type { PageContent, PageSlug } from '../types';

export const pages: Record<PageSlug, PageContent> = {
  home: {
    slug: 'home',
    seo: {
      title: 'applyspace - Your job search, finally in one space',
      description:
        'Search offers from Welcome to the Jungle, LinkedIn, Indeed and HelloWork, track every application, and prepare your interviews, all in one space.',
    },
    eyebrow: 'For job seekers',
    heading: 'Every offer, application and interview. One calm space.',
    intro:
      'Search offers from Welcome to the Jungle, LinkedIn, Indeed and HelloWork, track every application, and prepare your interviews, all in one space.',
    ctas: [
      { label: 'Get started free', href: '/login', kind: 'app' },
      { label: 'Download for macOS', href: '/download', kind: 'download' },
    ],
    note: 'Free for your first 15 applications. No card needed.',
    heroShot: {
      name: 'a1-board',
      alt: 'Board view with 20 applications in four columns: Saved, Applied, Interview, Offer. One card shows an interview date.',
      ratio: '16/10',
      caption: 'Applications, Board view',
      mobile: { name: 'a1-board-mobile', ratio: '4/5' },
    },
    sections: [
      {
        type: 'scatter',
        title: 'One application, five tools.',
        body: "The offer lives in a browser tab, the status in a spreadsheet, the recruiter's name in your email, the interview in your calendar and your notes somewhere else. applyspace keeps all of it together, for every application.",
        fragments: [
          { kind: 'tab', label: 'Browser tab', text: 'Product Designer - 34 tabs' },
          { kind: 'sheet', label: 'Spreadsheet', text: 'applications_v7_final.xlsx' },
          { kind: 'note', label: 'Notes', text: 'Interview Tues? ask about remote' },
          { kind: 'email', label: 'Email', text: 'Re: your application' },
          { kind: 'calendar', label: 'Calendar', text: 'Call with recruiter' },
        ],
      },
      {
        type: 'spotlight',
        anchor: 'job-offers',
        eyebrow: 'Job offers',
        title: 'Search every board at once.',
        body: 'Create a search profile once (title, city, contract, salary) and run it across Welcome to the Jungle, LinkedIn, Indeed and HelloWork from the desktop app. New offers land in your account, deduplicated.',
        bullets: ['Search profiles you can reuse', 'One list, no duplicates', 'Save an offer to your applications in one click'],
        link: { label: 'See how search works', href: '/product#offers-search' },
        shotSide: 'right',
        shot: {
          name: 'a5-search',
          alt: "Job offers search with the profile 'Product Designer, Paris, CDI' and eight results, each with its job board icon and a Save button",
          ratio: '4/3',
          caption: "Search profile 'Product Designer, Paris'",
          mobile: { name: 'a5-search-mobile', ratio: '4/5' },
        },
        inset: {
          name: 'a5-search-filters',
          alt: 'Close-up of the search profile filters: Product Designer, Paris, CDI, salary',
          ratio: '3/2',
        },
        boards: [
          { key: 'welcome-to-the-jungle', name: 'Welcome to the Jungle' },
          { key: 'linkedin', name: 'LinkedIn' },
          { key: 'indeed', name: 'Indeed' },
          { key: 'hellowork', name: 'HelloWork' },
        ],
      },
      {
        type: 'views',
        anchor: 'applications',
        eyebrow: 'Applications',
        title: 'See every application your way.',
        intro: 'Four views on the same data. Move a card, and the table, timeline and map follow.',
        views: [
          {
            key: 'board',
            label: 'Board',
            icon: 'board',
            shot: {
              name: 'a1-board',
              alt: 'Board view with 20 applications in four columns: Saved, Applied, Interview, Offer',
              ratio: '16/10',
              caption: 'Board. Drag applications from Saved to Offer.',
              mobile: { name: 'a1-board-mobile', ratio: '4/5' },
            },
          },
          {
            key: 'table',
            label: 'Table',
            icon: 'table',
            shot: {
              name: 'a2-table',
              alt: 'Table view of 20 applications sorted by last update, with company, role, salary and status columns',
              ratio: '16/10',
              caption: 'Table. Sort by date, company, salary or status.',
              mobile: { name: 'a2-table-mobile', ratio: '4/5' },
            },
          },
          {
            key: 'timeline',
            label: 'Timeline',
            icon: 'timeline',
            shot: {
              name: 'a3-timeline',
              alt: 'Timeline view over two weeks with applications sent, interviews and replies',
              ratio: '16/10',
              caption: "Timeline. See what happened, and what's next.",
              mobile: { name: 'a3-timeline-mobile', ratio: '4/5' },
            },
          },
          {
            key: 'map',
            label: 'Map',
            icon: 'map',
            shot: {
              name: 'a4-map',
              alt: 'Map view with application pins in Paris and Lyon and a list of remote applications',
              ratio: '16/10',
              caption: 'Map. See where your applications are, and how far.',
              mobile: { name: 'a4-map-mobile', ratio: '4/5' },
            },
          },
        ],
      },
      {
        type: 'spotlight',
        anchor: 'interviews',
        eyebrow: 'Interviews',
        title: 'Walk into every interview prepared.',
        body: "Each interview keeps its date, the people you meet, your notes and your questions, linked to the application. After the call, write down how it went while it's fresh.",
        bullets: ['Every round on one timeline', 'Notes and questions per interview', 'Linked to the offer and the company'],
        shotSide: 'left',
        shot: {
          name: 'a6-interview',
          alt: 'Second-round interview with its date, two interviewers, a notes block and three prepared questions',
          ratio: '4/3',
          caption: 'Second-round interview, notes',
          mobile: { name: 'a6-interview-mobile', ratio: '4/5' },
        },
        inset: {
          name: 'a6-interview-stepper',
          alt: 'Close-up of the round stepper: round 1 done, round 2 next',
          ratio: '3/2',
        },
      },
      {
        type: 'flow',
        anchor: 'profile',
        eyebrow: 'Profile',
        title: 'Your profile, filled from your resume.',
        body: 'Drop a PDF or DOCX, or your LinkedIn export. Your experience, education, languages and skills are filled in for you to review and edit.',
        caption: 'Resume to profile',
        steps: [
          { label: 'Drop your resume', shot: { name: 'a7-profile-drop', alt: 'The file camille-aubert-cv.pdf dropped on the import area', ratio: '4/3' } },
          { label: 'Fields are read', shot: { name: 'a7-profile-parsing', alt: 'Profile fields appearing while the resume is read', ratio: '4/3' } },
          { label: 'Review your profile', shot: { name: 'a7-profile-filled', alt: 'Filled profile with experience, education, languages and skills', ratio: '4/3' } },
        ],
      },
      {
        type: 'steps',
        title: 'From first search to signed offer.',
        items: [
          { title: 'Import your resume', text: 'Your profile is ready in a minute.' },
          { title: 'Search the boards', text: 'Run your search profiles from the desktop app.' },
          { title: 'Track your applications', text: 'Every status, document and contact together.' },
          { title: 'Prepare your interviews', text: 'Notes, questions and next steps per round.' },
        ],
      },
      {
        type: 'trust',
        title: 'Your job search stays yours.',
        intro: "Your current employer doesn't need to know. Neither does anyone else.",
        items: [
          { icon: 'lock', title: 'Private to your account', text: 'Your offers, applications and notes are scoped to your account. Nobody else can read them.' },
          { icon: 'analytics', title: 'Analytics only if you agree', text: 'Usage analytics are off until you opt in, and you can turn them off any time.' },
          { icon: 'ai', title: 'Your AI, your account', text: "AI features run on your own AI accounts. We don't resell your data or train AI on it." },
          { icon: 'leave', title: 'Leave whenever you want', text: 'Export your data or delete your account from Settings.' },
        ],
      },
      {
        type: 'plans',
        title: 'Less than a coffee a month.',
        intro: 'Start free. Upgrade when your search picks up.',
        variant: 'compact',
        footnote: 'All plans include search, the four application views, interviews and resume import.',
      },
      {
        type: 'facts',
        eyebrow: 'Product facts',
        title: 'What you get, in plain numbers.',
        items: [
          { value: '4', label: 'spaces', text: 'Job offers, Applications, Interviews and Profile.' },
          { value: '4', label: 'views of the same applications', text: 'Board, Table, Timeline and Map.' },
          { value: '4', label: 'job boards in one search', text: 'Welcome to the Jungle, LinkedIn, Indeed and HelloWork.' },
          { value: '€0', label: 'to start', text: 'Then €0.99 or €3.99 a month for more applications.' },
        ],
      },
      {
        type: 'faq',
        title: 'Questions, answered.',
        link: { label: 'Pricing questions', href: '/pricing' },
        items: [
          { question: 'Is applyspace free?', answer: 'Yes, for your first 15 applications. Plus (€0.99/month) and Max (€3.99/month) raise the limit.' },
          { question: 'Which job boards can I search?', answer: 'Welcome to the Jungle, LinkedIn, Indeed and HelloWork.' },
          { question: 'Why do I need the desktop app?', answer: 'Searches run from the desktop app, using your own sessions on the job boards. Results are saved to your account and visible on the web too.' },
          { question: 'Who can see my data?', answer: 'Only you. Your data is scoped to your account.' },
          { question: 'How does the AI work?', answer: 'AI features use your own AI account, so you stay in control of what is sent and to whom.' },
          { question: 'Can I import my resume?', answer: 'Yes: PDF, DOCX or your LinkedIn export.' },
        ],
      },
      {
        type: 'cta',
        title: 'Give your job search one space.',
        text: 'Free for your first 15 applications.',
        cta: { label: 'Get started free', href: '/login', kind: 'app' },
        secondary: { label: 'Download for macOS', href: '/download', kind: 'download' },
        shot: { name: 'a1-board', alt: 'The applications board', ratio: '16/10' },
      },
    ],
  },
  product: {
    slug: 'product',
    seo: {
      title: 'Product: search, track and prepare in one app',
      description: 'Job offers search, an applications hub with board, table, timeline and map, interview tracking and a resume-powered profile.',
    },
    heading: 'Everything for your job search, in one app',
    intro: 'From the first offer to the final interview, every space works on the same data.',
    sections: [
      { type: 'features' },
      {
        type: 'cta',
        title: 'See it with your own search',
        text: 'Free to start. Import your resume and set up in minutes.',
        cta: { label: 'Start for free', href: '/login', kind: 'app' },
      },
    ],
  },
  pricing: {
    slug: 'pricing',
    seo: {
      title: 'Pricing: Free, Plus and Max',
      description: 'Start free with 15 applications. Plus raises the cap to 99 and Max has no limits.',
    },
    heading: 'Start free, upgrade when you need more',
    intro: 'Pick the room you need for your search. Change plan at any time.',
    sections: [
      {
        type: 'plans',
        variant: 'full',
      },
      {
        type: 'faq',
        title: 'Frequently asked questions',
        items: [
          { question: 'Is applyspace free?', answer: 'Yes. The Free plan includes application tracking, interview preparation and the core tools, with a cap of 15 applications, one search profile and one interview template.' },
          { question: 'What counts as an application?', answer: 'Every application you save counts toward your cap. Free allows 15, Plus 99 and Max has no limit.' },
          { question: 'Can I change plan later?', answer: 'Yes. You can upgrade when you need more room and return to Free at any time.' },
          { question: 'What happens to my data if I go back to Free?', answer: 'Your data is kept. You return to the Free possibilities, which means a lower cap and fewer search profiles.' },
          { question: 'Does applyspace pay for AI?', answer: 'No. AI features run on your own AI accounts (Claude, OpenAI or Gemini), so you stay in control of the cost and of your documents.' },
          { question: 'Where is my data stored?', answer: 'Everything is stored in the cloud, in a hosted database with per-user access rules, so you find your search on any device.' },
        ],
      },
      {
        type: 'cta',
        title: 'Start on the Free plan',
        text: 'No card needed.',
        cta: { label: 'Start for free', href: '/login', kind: 'app' },
      },
    ],
  },
  resources: {
    slug: 'resources',
    seo: {
      title: 'Resources: guides for a calmer job search',
      description: 'Practical guides on searching, tracking applications and preparing interviews.',
    },
    heading: 'Resources',
    intro: 'Practical guides on searching, tracking and interviewing.',
    sections: [],
  },
};
