/**
 * Eval set of synthetic resumes (APP-108): English and French, one and two
 * columns (as the extractor reads them), different date and role styles. Every
 * name, company and contact is made up (example.com addresses, fictional
 * people); no real personal data. `expected` is lenient JSON that
 * `validateParsedResume` turns into a full ParsedResume.
 */

export interface Fixture {
  id: string;
  text: string;
  expected: Record<string, unknown>;
}

export const NOW = new Date('2026-10-10T00:00:00Z');

export const FIXTURES: Fixture[] = [
  {
    id: 'en-single-column',
    text: [
      'Jane Doe',
      'Senior Product Designer',
      'jane.doe@example.com | +33 6 12 34 56 78 | Paris, France',
      'linkedin.com/in/janedoe',
      '',
      'SUMMARY',
      'Product designer with 8 years of experience building B2B tools.',
      '',
      'EXPERIENCE',
      'Senior Product Designer - Acme Corp - Paris',
      'Jan 2021 - Present',
      '- Led the redesign of the analytics dashboard',
      '- Mentored 3 junior designers',
      '',
      'Product Designer - Beta Studio - Lyon',
      'Sep 2017 - Dec 2020',
      '- Shipped a mobile app used by 50,000 people',
      '',
      'EDUCATION',
      'Master in Design, Strate School of Design, 2015 - 2017',
      '',
      'SKILLS',
      'Figma, User research, Prototyping, Design systems',
      '',
      'LANGUAGES',
      'English (native), French (fluent)',
    ].join('\n'),
    expected: {
      firstName: 'Jane',
      lastName: 'Doe',
      email: 'jane.doe@example.com',
      phoneNumber: '+33 6 12 34 56 78',
      jobTitle: 'Senior Product Designer',
      location: 'Paris, France',
      seniority: 'senior',
      yearsOfExperience: 8,
      links: [{ url: 'linkedin.com/in/janedoe' }],
      experiences: [
        { companyName: 'Acme Corp', jobTitle: 'Senior Product Designer', location: 'Paris', startDate: 'Jan 2021', isCurrent: true },
        { companyName: 'Beta Studio', jobTitle: 'Product Designer', location: 'Lyon', startDate: 'Sep 2017', endDate: 'Dec 2020' },
      ],
      education: [{ school: 'Strate School of Design', degree: 'Master', field: 'Design', endDate: '2017' }],
      skills: [{ name: 'Figma' }, { name: 'User research' }, { name: 'Prototyping' }, { name: 'Design systems' }],
      languages: [{ name: 'English', level: 'native' }, { name: 'French', level: 'professional' }],
    },
  },
  {
    id: 'fr-single-column',
    text: [
      'Camille Martin',
      'Développeuse full stack',
      'camille.martin@example.fr · 06 12 34 56 78 · Nantes',
      '',
      'Profil',
      "Développeuse avec 6 ans d'expérience en TypeScript et Go.",
      '',
      'Expérience professionnelle',
      "Développeuse senior — Orange — Nantes\t2020 – Aujourd'hui",
      "Conception d'une plateforme de paiement.",
      'Développeuse — Capgemini — Rennes\t2016 – 2020',
      '',
      'Formation',
      "Diplôme d'ingénieur, INSA Rennes\t2013 – 2016",
      '',
      'Compétences',
      'TypeScript, Go, PostgreSQL, Docker',
      '',
      'Langues',
      'Français : langue maternelle',
      'Anglais : courant',
    ].join('\n'),
    expected: {
      firstName: 'Camille',
      lastName: 'Martin',
      email: 'camille.martin@example.fr',
      phoneNumber: '06 12 34 56 78',
      jobTitle: 'Développeuse full stack',
      location: 'Nantes',
      seniority: 'senior',
      yearsOfExperience: 6,
      experiences: [
        { companyName: 'Orange', jobTitle: 'Développeuse senior', location: 'Nantes', startDate: '2020', isCurrent: true },
        { companyName: 'Capgemini', jobTitle: 'Développeuse', location: 'Rennes', startDate: '2016', endDate: '2020' },
      ],
      education: [{ school: 'INSA Rennes', degree: "Diplôme d'ingénieur", startDate: '2013', endDate: '2016' }],
      skills: [{ name: 'TypeScript' }, { name: 'Go' }, { name: 'PostgreSQL' }, { name: 'Docker' }],
      languages: [{ name: 'Français', level: 'native' }, { name: 'Anglais', level: 'professional' }],
    },
  },
  {
    id: 'en-two-columns-sidebar-first',
    text: [
      'John Smith',
      'Staff Software Engineer',
      'john.smith@example.com',
      '+44 7700 900123',
      'London, UK',
      'github.com/jsmith',
      '',
      'SKILLS',
      'Python',
      'Go',
      'Kubernetes',
      '',
      'LANGUAGES',
      'English - native',
      'German - basic',
      '',
      'EXPERIENCE',
      'Staff Engineer at Gamma Ltd',
      '2018 - Present',
      'Built the data platform for 2M users.',
      '',
      'Software Engineer at Delta Inc',
      '2014 - 2018',
      'Maintained billing services.',
      '',
      'EDUCATION',
      'BSc Computer Science, Imperial College London, 2010 - 2013',
    ].join('\n'),
    expected: {
      firstName: 'John',
      lastName: 'Smith',
      email: 'john.smith@example.com',
      phoneNumber: '+44 7700 900123',
      jobTitle: 'Staff Software Engineer',
      location: 'London, UK',
      seniority: 'lead',
      yearsOfExperience: 12,
      links: [{ url: 'github.com/jsmith' }],
      experiences: [
        { companyName: 'Gamma Ltd', jobTitle: 'Staff Engineer', startDate: '2018', isCurrent: true },
        { companyName: 'Delta Inc', jobTitle: 'Software Engineer', startDate: '2014', endDate: '2018' },
      ],
      education: [{ school: 'Imperial College London', degree: 'BSc Computer Science', startDate: '2010', endDate: '2013' }],
      skills: [{ name: 'Python' }, { name: 'Go' }, { name: 'Kubernetes' }],
      languages: [{ name: 'English', level: 'native' }, { name: 'German', level: 'basic' }],
    },
  },
  {
    id: 'fr-since-and-months',
    text: [
      'Léa DUPONT',
      'Chargée de projet marketing',
      'lea.dupont@example.com | 07 98 76 54 32 | Lyon',
      'https://www.leadupont.fr',
      '',
      'Expérience',
      'Chargée de projet marketing — Danone — Paris',
      'Depuis mars 2022',
      'Pilotage de campagnes digitales',
      "Assistante marketing — L'Oréal — Clichy",
      'septembre 2019 – février 2022',
      '',
      'Formation',
      'Master Marketing Digital, Université Lyon 3, 2017 – 2019',
      'Licence Gestion, Université Lyon 3, 2014 – 2017',
      '',
      'Compétences',
      'SEO, Google Analytics, HubSpot',
      '',
      'Certifications',
      'Google Analytics Certification - Google - 2021',
      '',
      "Centres d'intérêt",
      'Voyages, photographie',
    ].join('\n'),
    expected: {
      firstName: 'Léa',
      lastName: 'Dupont',
      email: 'lea.dupont@example.com',
      phoneNumber: '07 98 76 54 32',
      jobTitle: 'Chargée de projet marketing',
      location: 'Lyon',
      seniority: 'senior',
      yearsOfExperience: 7,
      links: [{ url: 'https://www.leadupont.fr' }],
      experiences: [
        { companyName: 'Danone', jobTitle: 'Chargée de projet marketing', location: 'Paris', startDate: 'mars 2022', isCurrent: true },
        { companyName: "L'Oréal", jobTitle: 'Assistante marketing', location: 'Clichy', startDate: 'septembre 2019', endDate: 'février 2022' },
      ],
      education: [
        { school: 'Université Lyon 3', degree: 'Master Marketing Digital', startDate: '2017', endDate: '2019' },
        { school: 'Université Lyon 3', degree: 'Licence Gestion', startDate: '2014', endDate: '2017' },
      ],
      skills: [{ name: 'SEO' }, { name: 'Google Analytics' }, { name: 'HubSpot' }],
      certifications: [{ name: 'Google Analytics Certification', issuer: 'Google', date: '2021' }],
    },
  },
  {
    id: 'en-junior-student',
    text: [
      'Alex Johnson',
      'Computer Science Student',
      'alex.j@example.org',
      'Berlin, Germany',
      '',
      'EDUCATION',
      'BSc Computer Science',
      'Technical University of Berlin',
      '2021 - 2024',
      '',
      'EXPERIENCE',
      'Software Engineering Intern, Startup GmbH, Berlin',
      'Jun 2023 - Aug 2023',
      '- Built internal dashboards',
      '',
      'SKILLS',
      'JavaScript, React, SQL',
    ].join('\n'),
    expected: {
      firstName: 'Alex',
      lastName: 'Johnson',
      email: 'alex.j@example.org',
      jobTitle: 'Computer Science Student',
      location: 'Berlin, Germany',
      seniority: 'entry',
      yearsOfExperience: 0,
      experiences: [
        { companyName: 'Startup GmbH', jobTitle: 'Software Engineering Intern', location: 'Berlin', startDate: 'Jun 2023', endDate: 'Aug 2023' },
      ],
      education: [{ school: 'Technical University of Berlin', degree: 'BSc Computer Science', startDate: '2021', endDate: '2024' }],
      skills: [{ name: 'JavaScript' }, { name: 'React' }, { name: 'SQL' }],
    },
  },
  {
    id: 'fr-dates-first',
    text: [
      'Pierre Lefèvre',
      'Ingénieur DevOps',
      'pierre.lefevre@example.com',
      'Toulouse',
      '',
      'EXPÉRIENCE PROFESSIONNELLE',
      '2021 - 2024',
      'Ingénieur DevOps chez Airbus',
      '- Mise en place de la CI/CD',
      '- Migration vers Kubernetes',
      '2018 - 2021',
      'Technicien réseau chez Thales',
      '',
      'FORMATION',
      "Diplôme d'ingénieur, ENSEEIHT, 2018",
    ].join('\n'),
    expected: {
      firstName: 'Pierre',
      lastName: 'Lefèvre',
      email: 'pierre.lefevre@example.com',
      jobTitle: 'Ingénieur DevOps',
      location: 'Toulouse',
      seniority: 'senior',
      yearsOfExperience: 8,
      experiences: [
        { companyName: 'Airbus', jobTitle: 'Ingénieur DevOps', startDate: '2021', endDate: '2024' },
        { companyName: 'Thales', jobTitle: 'Technicien réseau', startDate: '2018', endDate: '2021' },
      ],
      education: [{ school: 'ENSEEIHT', degree: "Diplôme d'ingénieur", endDate: '2018' }],
    },
  },
];
