import type { Metadata } from 'next';
import { SITE_URL, isIndexable } from './env';
import { hreflang, locales, type Locale } from './i18n';
import { siteUrl } from './links';

type PageMeta = {
  locale: Locale;
  /** Path without locale prefix, e.g. `/pricing`. */
  path: string;
  /** Page title; the site name is appended by the root template unless `absoluteTitle`. */
  title: string;
  description: string;
  absoluteTitle?: boolean;
  noindex?: boolean;
  ogImageUrl?: string;
  type?: 'website' | 'article';
  publishedTime?: string;
  modifiedTime?: string;
};

/** Open Graph card generated by /og, or the editor's image. Titles are capped to keep the card readable. */
export function ogImage(title: string, override?: string) {
  if (override) return override;
  return `${SITE_URL}/og?title=${encodeURIComponent(title.slice(0, 90))}`;
}

export function buildMetadata(m: PageMeta): Metadata {
  const url = siteUrl(m.locale, m.path);
  const image = ogImage(m.title, m.ogImageUrl);
  const languages: Record<string, string> = {};
  for (const l of locales) languages[hreflang[l]] = siteUrl(l, m.path);
  languages['x-default'] = siteUrl('en', m.path);
  const index = isIndexable && !m.noindex;

  return {
    title: m.absoluteTitle ? { absolute: m.title } : m.title,
    description: m.description,
    alternates: { canonical: url, languages },
    robots: index ? { index: true, follow: true } : { index: false, follow: false },
    openGraph: {
      type: m.type ?? 'website',
      url,
      siteName: 'applyspace',
      title: m.title,
      description: m.description,
      locale: m.locale,
      images: [{ url: image, width: 1200, height: 630, alt: m.title }],
      ...(m.type === 'article' ? { publishedTime: m.publishedTime, modifiedTime: m.modifiedTime } : {}),
    },
    twitter: { card: 'summary_large_image', title: m.title, description: m.description, images: [image] },
  };
}
