import {
  CONFLICT_COLUMNS,
  DEMO_TABLES,
  buildDemoDataset,
  summarize,
  type Cell,
  type DemoDataset,
  type DemoTable,
  type Row,
} from './dataset';
import { DEFAULT_DEMO_EMAIL, DEMO_EMAIL_DOMAIN } from './identity';

/**
 * Renders the demo dataset as one reviewable SQL script (what the founder reads
 * before giving the go). The script is a single `do` block, so it is atomic, and
 * it replaces the demo user's data: it deletes every row of that user in the
 * seeded tables and inserts the dataset again. It never creates the auth user
 * and never touches Storage (see docs/demo-account.md for the files).
 */

/** Placeholder user id used while building; replaced by `v_user` in the output. */
const USER_SENTINEL = '00000000-0000-4000-8000-0000000000de';

/** Default anchor of the generated SQL. Pass `--anchor` for fresher dates. */
export const DEFAULT_ANCHOR = '2026-10-12';

const quote = (text: string) => `'${text.replace(/'/g, "''")}'`;

function textExpr(text: string): string {
  if (!text.includes(USER_SENTINEL)) return quote(text);
  return text
    .split(USER_SENTINEL)
    .map((part, index, parts) => (index < parts.length - 1 ? [part && quote(part), 'v_user::text'] : [part && quote(part)]))
    .flat()
    .filter(Boolean)
    .join(' || ');
}

function literal(value: Cell): string {
  if (value === null) return 'null';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'string') return value === USER_SENTINEL ? 'v_user' : textExpr(value);
  if (Array.isArray(value) && value.every((v) => typeof v === 'string')) {
    if (value.length === 0) return `'{}'::text[]`;
    return `array[${(value as string[]).map(quote).join(', ')}]::text[]`;
  }
  return `${quote(JSON.stringify(value))}::jsonb`;
}

function insertStatement(table: string, rows: Row[]): string {
  if (rows.length === 0) return '';
  const columns = Object.keys(rows[0]).sort();
  const signature = columns.join(',');
  for (const row of rows) {
    if (Object.keys(row).sort().join(',') !== signature) {
      throw new Error(`Rows of ${table} do not share the same columns`);
    }
  }
  const values = rows.map((row) => `    (${columns.map((c) => literal(row[c])).join(', ')})`).join(',\n');
  return `  insert into public.${table} (${columns.join(', ')}) values\n${values};\n`;
}

const sqlText = (text: string) => quote(text);

export interface SqlOptions {
  anchor?: string;
  /** Email of the demo auth user. Must be on the reserved domain. */
  email?: string;
}

export function generateSeedSql({ anchor = DEFAULT_ANCHOR, email = DEFAULT_DEMO_EMAIL }: SqlOptions = {}): string {
  if (!email.toLowerCase().endsWith(`@${DEMO_EMAIL_DOMAIN}`)) {
    throw new Error(`The demo email must be on ${DEMO_EMAIL_DOMAIN}`);
  }
  const dataset: DemoDataset = buildDemoDataset({ anchor, userId: USER_SENTINEL });
  const counts = summarize(dataset);
  const a = dataset.account;

  const requiredTables = ['languages', 'certifications', 'profile_links', 'projects', 'volunteering', 'publications', 'application_documents', 'offer_sources'];
  const requiredColumns: Array<[string, string]> = [
    ['accounts', 'phone_number'], ['accounts', 'selected_plan'], ['profiles', 'seniority'], ['experiences', 'achievements'],
    ['applications', 'location'], ['applications', 'deadline_at'], ['searches', 'job_titles'], ['offers', 'dedupe_key'],
  ];

  const deleteOrder = [...DEMO_TABLES].reverse() as DemoTable[];
  const out: string[] = [];
  out.push(`-- ApplySpace demo account seed. GENERATED by packages/core (see docs/demo-account.md): do not edit by hand.
-- Regenerate: pnpm demo:sql [--anchor YYYY-MM-DD] [--email demo@${DEMO_EMAIL_DOMAIN}]
-- Anchor day: ${anchor} (every date in the data is relative to it).
-- Status: NOT APPLIED. It runs only after the founder's explicit go.
--
-- What it does, in one transaction:
--   1. checks the migrations it needs are applied (profile data model, applications hub);
--   2. finds the demo auth user by email (${email}); it never creates the user;
--   3. sets that account to the Max plan, onboarded, with a complete profile header;
--   4. deletes every row of THAT user in: ${deleteOrder.join(', ')}, search_no_gos;
--   5. inserts the fictional dataset again: ${Object.entries(counts).map(([k, v]) => `${k} ${v}`).join(', ')}.
-- Re-running it resets the demo account to this exact state. It touches no other user and no Storage object.
-- Guard: it refuses to run unless the user's email is on ${DEMO_EMAIL_DOMAIN}.

do $seed$
declare
  v_email constant text := ${sqlText(email)};
  v_user uuid;
begin
  -- 1. Prerequisites ----------------------------------------------------------
  if ${requiredTables.map((t) => `to_regclass('public.${t}') is null`).join('\n     or ')} then
    raise exception 'Demo seed: apply the migrations 20261010000000_profile_data_model and 20261010120000_applications_hub first';
  end if;
  if ${requiredColumns
    .map(([t, c]) => `not exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = '${t}' and column_name = '${c}')`)
    .join('\n     or ')} then
    raise exception 'Demo seed: a column is missing, apply the pending migrations first';
  end if;

  -- 2. The demo user (created beforehand by the founder) ------------------------
  if lower(v_email) not like '%@${DEMO_EMAIL_DOMAIN}' then
    raise exception 'Demo seed: the demo email must be on ${DEMO_EMAIL_DOMAIN}';
  end if;
  select id into v_user from auth.users where lower(email) = lower(v_email);
  if v_user is null then
    raise exception 'Demo seed: no auth user with email %. Create it first (dashboard > Authentication > Users, auto confirm).', v_email;
  end if;

  -- 3. Account (plan first: plan limits read it) --------------------------------
  insert into public.accounts (id, email) values (v_user, v_email) on conflict (id) do nothing;
  update public.accounts set
    plan = ${quote(a.plan)}, selected_plan = ${quote(a.selected_plan)}, first_name = ${quote(a.first_name)}, last_name = ${quote(a.last_name)},
    full_name = ${quote(a.full_name)}, locale = ${quote(a.locale)}, theme_mode = ${quote(a.theme_mode)}, onboarded_at = ${quote(a.onboarded_at)},
    availability = ${quote(a.availability)}, current_place = ${literal(a.current_place)}, linkedin_url = ${quote(a.linkedin_url)},
    website_url = ${quote(a.website_url)}, phone_number = ${quote(a.phone_number)}, writing_style = ${literal(a.writing_style)}
  where id = v_user;

  -- 4. Reset: this user's rows only ---------------------------------------------
  delete from public.search_no_gos where user_id = v_user;
${deleteOrder.map((t) => `  delete from public.${t} where user_id = v_user;`).join('\n')}

  -- 5. Dataset --------------------------------------------------------------------`);
  for (const table of DEMO_TABLES) out.push(insertStatement(table, dataset.tables[table]));
  const noGoLines = dataset.searchNoGos.map(
    (n) =>
      `  insert into public.search_no_gos (user_id, search_id, no_go_id)\n  select v_user, ${quote(n.search_id)}::uuid, id from public.no_gos where user_id is null and key = ${quote(n.no_go_key)};\n`,
  );
  out.push(noGoLines.join(''));
  out.push(`  raise notice 'Demo seed done for %', v_email;
end
$seed$;
`);
  return out.join('\n');
}

export { CONFLICT_COLUMNS };
